import pytest
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.conversation import ChatMessage, Conversation, MessageRole
from app.services.chat_service import chat_service


@pytest.mark.asyncio
async def test_chat_persistence_flow(db_session: AsyncSession, test_user, test_org):
    """
    Integration test for Chat Service persistence.
    Verifies that processing a query creates a conversation and saves messages.
    """

    # 1. New Conversation Flow
    query = "What is the status of the project?"

    # Mock AI Service to avoid real OpenAI calls
    from unittest.mock import AsyncMock, patch

    with patch(
        "app.services.chat_service.ai_service.summarize_activities", new_callable=AsyncMock
    ) as mock_ai:
        mock_ai.return_value = "The project is on track."

        with patch(
            "app.services.ai_service.ai_service.generate_title", new_callable=AsyncMock
        ) as mock_title:
            mock_title.return_value = "AI Generated Title"

            # Call process_query without conversation_id
            result = await chat_service.process_query(
                db_session, query=query, user_id=test_user.id, org_id=str(test_org.id)
            )

            # Verify result structure
            assert result["answer"] == "The project is on track."
            assert result["conversation_id"] is not None
            conversation_id = result["conversation_id"]

            # Verify persistence in DB
            # Check Conversation
            stmt = select(Conversation).where(Conversation.id == conversation_id)
            res = await db_session.execute(stmt)
            conversation = res.scalar_one_or_none()
            assert conversation is not None
            assert conversation.user_id == test_user.id

            # Title should have been generated by our mock
            assert conversation.title == "AI Generated Title"

            # Check Messages
            # Should have 2 messages: User and Assistant
            stmt_msgs = (
                select(ChatMessage)
                .where(ChatMessage.conversation_id == conversation_id)
                .order_by(ChatMessage.created_at)
            )
            res_msgs = await db_session.execute(stmt_msgs)
            messages = res_msgs.scalars().all()

            assert len(messages) == 2
            assert messages[0].role == MessageRole.USER
            assert messages[0].content == query

            assert messages[1].role == MessageRole.ASSISTANT
            assert messages[1].content == "The project is on track."

    # 2. Existing Conversation Flow
    query_2 = "Tell me more."

    with patch(
        "app.services.chat_service.ai_service.summarize_activities", new_callable=AsyncMock
    ) as mock_ai:
        mock_ai.return_value = "Here are more details."

        result_2 = await chat_service.process_query(
            db_session,
            query=query_2,
            user_id=test_user.id,
            org_id=str(test_org.id),
            conversation_id=conversation_id,
        )

        assert result_2["conversation_id"] == conversation_id

        # Verify chat history persistence in DB (done below) and usage in AI service
        assert mock_ai.call_count == 1
        call_kwargs = mock_ai.call_args.kwargs
        chat_history = call_kwargs.get("chat_history")
        assert chat_history is not None
        assert len(chat_history) == 2
        assert chat_history[0]["role"] == MessageRole.USER.value
        assert chat_history[0]["content"] == query
        assert chat_history[1]["role"] == MessageRole.ASSISTANT.value
        assert chat_history[1]["content"] == "The project is on track."

        # Verify persistence of new messages
        res_msgs_2 = await db_session.execute(stmt_msgs)
        messages_2 = res_msgs_2.scalars().all()

        assert len(messages_2) == 4  # 2 previous + 2 new
        assert messages_2[2].role == MessageRole.USER
        assert messages_2[2].content == query_2
        assert messages_2[3].role == MessageRole.ASSISTANT
        assert messages_2[3].content == "Here are more details."
