"""Add value_tags column to Activity

Revision ID: 874d6f5559b1
Revises: 7884dd46a3c3
Create Date: 2026-01-05 22:24:34.086105+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "874d6f5559b1"
down_revision: str | Sequence[str] | None = "7884dd46a3c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("value_tags", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "value_tags")
    # ### end Alembic commands ###
