"""Add context enrichment fields to Activity

Revision ID: 7884dd46a3c3
Revises: cc4ab63a77d3
Create Date: 2026-01-05 22:03:59.367182+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7884dd46a3c3"
down_revision: str | Sequence[str] | None = "cc4ab63a77d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("files_touched", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("activities", sa.Column("labels", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("activities", sa.Column("linked_issues", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "linked_issues")
    op.drop_column("activities", "labels")
    op.drop_column("activities", "files_touched")
    # ### end Alembic commands ###
