"""Add pending_invitations table

Revision ID: 072e2f4beb3e
Revises: 8c904c0f89b1
Create Date: 2026-02-04 15:58:30.936811+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "072e2f4beb3e"
down_revision: str | Sequence[str] | None = "8c904c0f89b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_invitations",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("team_ids", postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "EXPIRED", "REVOKED", name="invitationstatus"),
            nullable=False,
        ),
        sa.Column("invited_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["accepted_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_pending_invitations_email"), "pending_invitations", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_pending_invitations_invited_by_id"),
        "pending_invitations",
        ["invited_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_invitations_organization_id"),
        "pending_invitations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_pending_invite_expires", "pending_invitations", ["expires_at", "status"], unique=False
    )
    op.create_index(
        "ix_pending_invite_unique",
        "pending_invitations",
        ["organization_id", "email"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_pending_invite_unique",
        table_name="pending_invitations",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_pending_invite_expires", table_name="pending_invitations")
    op.drop_index(op.f("ix_pending_invitations_organization_id"), table_name="pending_invitations")
    op.drop_index(op.f("ix_pending_invitations_invited_by_id"), table_name="pending_invitations")
    op.drop_index(op.f("ix_pending_invitations_email"), table_name="pending_invitations")
    op.drop_table("pending_invitations")
    # ### end Alembic commands ###
