"""add_occurred_at_to_activity

Revision ID: cc4ab63a77d3
Revises: 95fcc474826d
Create Date: 2026-01-05 20:55:04.970454+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc4ab63a77d3"
down_revision: str | Sequence[str] | None = "95fcc474826d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "occurred_at")
    # ### end Alembic commands ###
