"""add_idempotency_and_stakeholder_tables

Revision ID: 44f0960ef61c
Revises: f33db4ck0004
Create Date: 2026-01-29 01:35:46.314978+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44f0960ef61c"
down_revision: str | Sequence[str] | None = "f33db4ck0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derived_artifacts",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("pipeline_version", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_ref", sa.Text(), nullable=True),
        sa.Column("supersedes_artifact_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_artifact_id"],
            ["derived_artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "artifact_type",
            "pipeline_version",
            "content_hash",
            name="uq_artifact",
        ),
    )
    op.create_index(
        op.f("ix_derived_artifacts_entity_id"), "derived_artifacts", ["entity_id"], unique=False
    )
    op.create_table(
        "ingest_event_ledger",
        sa.Column("delivery_id", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processing_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id"),
    )
    op.create_index(
        op.f("ix_ingest_event_ledger_repo_full_name"),
        "ingest_event_ledger",
        ["repo_full_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_event_ledger_status"), "ingest_event_ledger", ["status"], unique=False
    )
    op.create_table(
        "public_references",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("team_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("external_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("team_id", "entity_type", "entity_id", name="uq_ref_entity"),
    )
    op.create_index(
        op.f("ix_public_references_team_id"), "public_references", ["team_id"], unique=False
    )
    op.add_column("activities", sa.Column("github_node_id", sa.String(length=100), nullable=True))
    op.add_column("activities", sa.Column("state", sa.String(length=20), nullable=True))
    op.add_column(
        "activities", sa.Column("state_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "activities", sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint(None, "activities", ["github_node_id"])
    op.create_index("ix_feedback_generation", "feedback", ["generation_id"], unique=False)
    op.create_index("ix_feedback_prompt_version", "feedback", ["prompt_version_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_feedback_prompt_version", table_name="feedback")
    op.drop_index("ix_feedback_generation", table_name="feedback")
    op.drop_constraint(None, "activities", type_="unique")
    op.drop_column("activities", "last_event_at")
    op.drop_column("activities", "state_updated_at")
    op.drop_column("activities", "state")
    op.drop_column("activities", "github_node_id")
    op.drop_index(op.f("ix_public_references_team_id"), table_name="public_references")
    op.drop_table("public_references")
    op.drop_index(op.f("ix_ingest_event_ledger_status"), table_name="ingest_event_ledger")
    op.drop_index(op.f("ix_ingest_event_ledger_repo_full_name"), table_name="ingest_event_ledger")
    op.drop_table("ingest_event_ledger")
    op.drop_index(op.f("ix_derived_artifacts_entity_id"), table_name="derived_artifacts")
    op.drop_table("derived_artifacts")
    # ### end Alembic commands ###
