"""add_magic_links_table

Revision ID: e3acc651357b
Revises: 09c620df0446
Create Date: 2026-01-03 16:52:18.455226+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3acc651357b"
down_revision: str | Sequence[str] | None = "09c620df0446"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magic_links",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_magic_links_email"), "magic_links", ["email"], unique=False)
    op.create_index(op.f("ix_magic_links_token"), "magic_links", ["token"], unique=True)
    op.create_index(op.f("ix_magic_links_user_id"), "magic_links", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_magic_links_user_id"), table_name="magic_links")
    op.drop_index(op.f("ix_magic_links_token"), table_name="magic_links")
    op.drop_index(op.f("ix_magic_links_email"), table_name="magic_links")
    op.drop_table("magic_links")
    # ### end Alembic commands ###
