"""add_multitenancy_tables

Revision ID: 09c620df0446
Revises: 6c4953802868
Create Date: 2026-01-03 16:34:39.855897+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09c620df0446"
down_revision: str | Sequence[str] | None = "6c4953802868"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create new tables first
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("plan", sa.Enum("FREE", "PRO", "ENTERPRISE", name="plantype"), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "organization_settings",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("devbridge_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("slack_webhook_url", sa.String(length=500), nullable=True),
        sa.Column("github_app_installation_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id"),
    )
    op.create_table(
        "teams",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "slug", name="uq_team_org_slug"),
    )
    op.create_index(op.f("ix_teams_organization_id"), "teams", ["organization_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("team_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "role", sa.Enum("OWNER", "ADMIN", "MEMBER", "VIEWER", name="memberrole"), nullable=False
        ),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", "team_id", name="uq_membership"),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_team_id"), "memberships", ["team_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)

    # 2. Add organization_id to repositories as NULLABLE first
    op.add_column(
        "repositories", sa.Column("organization_id", sa.UUID(as_uuid=False), nullable=True)
    )
    op.add_column("repositories", sa.Column("team_id", sa.UUID(as_uuid=False), nullable=True))

    # 3. Create a default organization and backfill existing repositories
    conn = op.get_bind()
    default_org_id = "00000000-0000-0000-0000-000000000001"

    # Insert default organization
    conn.execute(
        sa.text(
            """
            INSERT INTO organizations (id, name, slug, plan, created_at, updated_at)
            VALUES (:id, 'Default Organization', 'default', 'FREE', NOW(), NOW())
            ON CONFLICT (id) DO NOTHING
            """
        ),
        {"id": default_org_id},
    )

    # Backfill all existing repositories with default org
    conn.execute(
        sa.text(
            """
            UPDATE repositories
            SET organization_id = :org_id
            WHERE organization_id IS NULL
            """
        ),
        {"org_id": default_org_id},
    )

    # 4. Now set organization_id as NOT NULL
    op.alter_column("repositories", "organization_id", nullable=False)

    # 5. Continue with other changes
    op.alter_column("repositories", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=False)
    op.create_index(
        op.f("ix_repositories_organization_id"), "repositories", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_repositories_team_id"), "repositories", ["team_id"], unique=False)
    op.create_unique_constraint("uq_repo_org_name", "repositories", ["organization_id", "name"])
    op.create_foreign_key(None, "repositories", "teams", ["team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(
        None, "repositories", "organizations", ["organization_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repositories", type_="foreignkey")
    op.drop_constraint(None, "repositories", type_="foreignkey")
    op.drop_constraint("uq_repo_org_name", "repositories", type_="unique")
    op.drop_index(op.f("ix_repositories_team_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_organization_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=True)
    op.alter_column("repositories", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("repositories", "team_id")
    op.drop_column("repositories", "organization_id")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_team_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_teams_organization_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_table("organization_settings")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
