"""Add context fields to conversations

Revision ID: 196dbefb24e2
Revises: d1e2f3g4h5i6
Create Date: 2026-01-16 18:23:37.244814+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "196dbefb24e2"
down_revision: str | Sequence[str] | None = "d1e2f3g4h5i6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activities",
        "review_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "rework_iterations",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "comments_received",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "is_reverted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "code_reviews",
        "comments_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.drop_constraint(op.f("uq_review_activity_review_id"), "code_reviews", type_="unique")
    op.alter_column(
        "contributor_stats",
        "commits",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "prs_created",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "prs_merged",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "reviews_given",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "issues_closed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "additions",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "deletions",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "comments_given",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.add_column("conversations", sa.Column("team_id", sa.UUID(as_uuid=False), nullable=True))
    op.add_column("conversations", sa.Column("persona", sa.String(length=50), nullable=True))
    op.add_column("conversations", sa.Column("days", sa.Integer(), nullable=True))
    op.add_column(
        "conversations",
        sa.Column("repositories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(op.f("ix_conversations_team_id"), "conversations", ["team_id"], unique=False)
    op.create_foreign_key(None, "conversations", "teams", ["team_id"], ["id"], ondelete="SET NULL")
    op.alter_column(
        "developer_profiles",
        "total_commits",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_prs_created",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_prs_merged",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_reviews_given",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_issues_closed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_lines_added",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "developer_profiles",
        "total_lines_deleted",
        existing_type=sa.BIGINT(),
        nullable=True,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.drop_constraint(op.f("uq_issue_repo_number"), "issues", type_="unique")
    op.drop_index(
        op.f("ix_report_templates_is_default"),
        table_name="report_templates",
        postgresql_where="(is_default = true)",
    )
    op.drop_index(op.f("ix_reports_generated_at"), table_name="reports")
    op.drop_index(op.f("ix_team_repositories_repository_id"), table_name="team_repositories")
    op.drop_index(op.f("ix_team_repositories_team_id"), table_name="team_repositories")
    op.drop_column("team_repositories", "added_at")
    op.drop_constraint(op.f("uq_team_org_slug"), "teams", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_team_org_slug"),
        "teams",
        ["organization_id", "slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "team_repositories",
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_team_repositories_team_id"), "team_repositories", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_repositories_repository_id"),
        "team_repositories",
        ["repository_id"],
        unique=False,
    )
    op.create_index(op.f("ix_reports_generated_at"), "reports", ["generated_at"], unique=False)
    op.create_index(
        op.f("ix_report_templates_is_default"),
        "report_templates",
        ["is_default"],
        unique=False,
        postgresql_where="(is_default = true)",
    )
    op.create_unique_constraint(
        op.f("uq_issue_repo_number"),
        "issues",
        ["repository_id", "issue_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "developer_profiles",
        "total_lines_deleted",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "developer_profiles",
        "total_lines_added",
        existing_type=sa.BIGINT(),
        nullable=False,
        existing_server_default=sa.text("'0'::bigint"),
    )
    op.alter_column(
        "developer_profiles",
        "total_issues_closed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_reviews_given",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_prs_merged",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_prs_created",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "developer_profiles",
        "total_commits",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_index(op.f("ix_conversations_team_id"), table_name="conversations")
    op.drop_column("conversations", "repositories")
    op.drop_column("conversations", "days")
    op.drop_column("conversations", "persona")
    op.drop_column("conversations", "team_id")
    op.alter_column(
        "contributor_stats",
        "comments_given",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "deletions",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "additions",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "issues_closed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "reviews_given",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "prs_merged",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "prs_created",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "contributor_stats",
        "commits",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.create_unique_constraint(
        op.f("uq_review_activity_review_id"),
        "code_reviews",
        ["activity_id", "review_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "code_reviews",
        "comments_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "is_reverted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "activities",
        "comments_received",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "rework_iterations",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "activities",
        "review_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
